/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 jet.gltf 
Author: McCarthy3D (https://sketchfab.com/joshuawatt811)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/heavy-class-firefly-8d6694aa551942f1a262e2444fe9a109
Title: Heavy Class Firefly
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/jet.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="297fd0f2628b41758f36adfa01c735e6fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Firefly_Ctrl" position={[300, 1356.301, 41.853]} rotation={[0.003, -0.008, 0.118]} scale={1.25}>
                  <group name="Serenity" position={[-4.237, 31.61, -485.038]}>
                    <group name="Exterior" position={[4.237, 116.876, 199.926]}>
                      <group name="R_Engine" position={[-2129.556, -132.306, 67.153]} rotation={[0.255, 0, 0]}>
                        <group name="Engine_Parts" position={[-84.514, 0, 54.339]}>
                          <group name="Fan_01_Rot" position={[12.471, 0, 1043.166]}>
                            <group name="Fan_01">
                              <mesh name="Fan_01_Light_Metal_Mat_0" geometry={nodes.Fan_01_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                            </group>
                          </group>
                          <group name="Fan_02_Rot" position={[12.471, 0, 989.185]}>
                            <group name="Fan_02">
                              <mesh name="Fan_02_Light_Metal_Mat_0" geometry={nodes.Fan_02_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                            </group>
                          </group>
                          <group name="Fan_03_Rot" position={[12.471, 0, 766.77]}>
                            <group name="Fan_03">
                              <mesh name="Fan_03_Light_Metal_Mat_0" geometry={nodes.Fan_03_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                            </group>
                          </group>
                          <group name="Turbine_Rot" position={[12.471, 0, 420.827]}>
                            <group name="Turbine_01">
                              <mesh name="Turbine_01_Light_Metal_Mat_0" geometry={nodes.Turbine_01_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                            </group>
                          </group>
                          <group name="Flap_4" position={[12.471, 349.635, -695.955]}>
                            <group name="polySurface134" position={[-90.385, 4.697, 300.755]} rotation={[0.083, 0, 0]}>
                              <mesh name="polySurface134_Light_Metal_Mat_0" geometry={nodes.polySurface134_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                              <mesh name="polySurface134_Dark_Metal_Mat_0" geometry={nodes.polySurface134_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                              <mesh name="polySurface134_Plating_Mat_0" geometry={nodes.polySurface134_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                            </group>
                          </group>
                          <group name="Flap_3" position={[-337.164, 0, -695.955]}>
                            <group name="polySurface135" position={[-4.697, 82.022, 300.755]} rotation={[0, 0.083, 0]}>
                              <mesh name="polySurface135_Light_Metal_Mat_0" geometry={nodes.polySurface135_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                              <mesh name="polySurface135_Dark_Metal_Mat_0" geometry={nodes.polySurface135_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                              <mesh name="polySurface135_Plating_Mat_0" geometry={nodes.polySurface135_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                            </group>
                          </group>
                          <group name="Flap_2" position={[362.107, 0, -695.955]}>
                            <group name="polySurface137" position={[4.698, 82.022, 300.755]} rotation={[0, -0.066, 0]}>
                              <mesh name="polySurface137_Light_Metal_Mat_0" geometry={nodes.polySurface137_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                              <mesh name="polySurface137_Dark_Metal_Mat_0" geometry={nodes.polySurface137_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                              <mesh name="polySurface137_Plating_Mat_0" geometry={nodes.polySurface137_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                            </group>
                          </group>
                          <group name="Flap_1" position={[12.472, -349.635, -695.955]}>
                            <group name="polySurface136" position={[-90.385, -4.697, 300.755]} rotation={[-0.066, 0.017, 0.001]}>
                              <mesh name="polySurface136_Light_Metal_Mat_0" geometry={nodes.polySurface136_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                              <mesh name="polySurface136_Dark_Metal_Mat_0" geometry={nodes.polySurface136_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                              <mesh name="polySurface136_Plating_Mat_0" geometry={nodes.polySurface136_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                            </group>
                          </group>
                          <group name="polySurface77" position={[12.471, 460.733, 201.417]}>
                            <mesh name="polySurface77_Plating_Mat_0" geometry={nodes.polySurface77_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface77_Dark_Metal_Mat_0" geometry={nodes.polySurface77_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface80" position={[-201.204, 383.495, 201.417]}>
                            <mesh name="polySurface80_Plating_Mat_0" geometry={nodes.polySurface80_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface80_Dark_Metal_Mat_0" geometry={nodes.polySurface80_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface81" position={[-371.024, 213.675, 201.417]}>
                            <mesh name="polySurface81_Plating_Mat_0" geometry={nodes.polySurface81_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface81_Dark_Metal_Mat_0" geometry={nodes.polySurface81_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface82" position={[-448.262, 0, 201.417]}>
                            <mesh name="polySurface82_Plating_Mat_0" geometry={nodes.polySurface82_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface82_Dark_Metal_Mat_0" geometry={nodes.polySurface82_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface83" position={[-371.024, -213.675, 201.417]}>
                            <mesh name="polySurface83_Plating_Mat_0" geometry={nodes.polySurface83_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface83_Dark_Metal_Mat_0" geometry={nodes.polySurface83_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface84" position={[-201.204, -383.495, 201.417]}>
                            <mesh name="polySurface84_Plating_Mat_0" geometry={nodes.polySurface84_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface84_Dark_Metal_Mat_0" geometry={nodes.polySurface84_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface85" position={[12.471, -460.733, 201.417]}>
                            <mesh name="polySurface85_Plating_Mat_0" geometry={nodes.polySurface85_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface85_Dark_Metal_Mat_0" geometry={nodes.polySurface85_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface86" position={[226.146, -383.495, 201.417]}>
                            <mesh name="polySurface86_Plating_Mat_0" geometry={nodes.polySurface86_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface86_Dark_Metal_Mat_0" geometry={nodes.polySurface86_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface87" position={[395.966, -213.675, 201.417]}>
                            <mesh name="polySurface87_Plating_Mat_0" geometry={nodes.polySurface87_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface87_Dark_Metal_Mat_0" geometry={nodes.polySurface87_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface89" position={[395.966, 213.675, 201.417]}>
                            <mesh name="polySurface89_Plating_Mat_0" geometry={nodes.polySurface89_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface89_Dark_Metal_Mat_0" geometry={nodes.polySurface89_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface90" position={[226.146, 383.495, 201.417]}>
                            <mesh name="polySurface90_Plating_Mat_0" geometry={nodes.polySurface90_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface90_Dark_Metal_Mat_0" geometry={nodes.polySurface90_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                        </group>
                        <group name="Engine_Body" position={[49.914, 0, 0]}>
                          <mesh name="Engine_Body_Plating_Mat_0" geometry={nodes.Engine_Body_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                          <mesh name="Engine_Body_Dark_Metal_Mat_0" geometry={nodes.Engine_Body_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          <mesh name="Engine_Body_Light_Metal_Mat_0" geometry={nodes.Engine_Body_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                          <mesh name="Engine_Body_Light_Mat_0" geometry={nodes.Engine_Body_Light_Mat_0.geometry} material={materials.Light_Mat} />
                        </group>
                      </group>
                      <group name="L_Engine" position={[2129.556, -184.645, 66.594]} rotation={[-0.236, 0, 0]}>
                        <group name="Engine_Parts_1" position={[84.514, 0, 54.339]}>
                          <group name="Fan_01_Rot_1" position={[-12.471, 0, 1043.166]}>
                            <group name="Fan_01_1">
                              <mesh name="Fan_01_Light_Metal_Mat_0_1" geometry={nodes.Fan_01_Light_Metal_Mat_0_1.geometry} material={materials.Light_Metal_Mat} />
                            </group>
                          </group>
                          <group name="Fan_02_Rot_1" position={[-12.471, 0, 989.185]}>
                            <group name="Fan_02_1">
                              <mesh name="Fan_02_Light_Metal_Mat_0_1" geometry={nodes.Fan_02_Light_Metal_Mat_0_1.geometry} material={materials.Light_Metal_Mat} />
                            </group>
                          </group>
                          <group name="Fan_03_Rot_1" position={[-12.471, 0, 766.77]}>
                            <group name="Fan_03_1">
                              <mesh name="Fan_03_Light_Metal_Mat_0_1" geometry={nodes.Fan_03_Light_Metal_Mat_0_1.geometry} material={materials.Light_Metal_Mat} />
                            </group>
                          </group>
                          <group name="Turbine_Rot_1" position={[-12.471, 0, 420.827]}>
                            <group name="Turbine_01_1">
                              <mesh name="Turbine_01_Light_Metal_Mat_0_1" geometry={nodes.Turbine_01_Light_Metal_Mat_0_1.geometry} material={materials.Light_Metal_Mat} />
                            </group>
                          </group>
                          <group name="Flap_4_1" position={[-12.471, 349.635, -695.955]}>
                            <group name="polySurface134_1" position={[90.385, 4.697, 300.755]} rotation={[0.271, 0, 0]}>
                              <mesh name="polySurface134_Light_Metal_Mat_0_1" geometry={nodes.polySurface134_Light_Metal_Mat_0_1.geometry} material={materials.Light_Metal_Mat} />
                              <mesh name="polySurface134_Dark_Metal_Mat_0_1" geometry={nodes.polySurface134_Dark_Metal_Mat_0_1.geometry} material={materials.Dark_Metal_Mat} />
                              <mesh name="polySurface134_Plating_Mat_0_1" geometry={nodes.polySurface134_Plating_Mat_0_1.geometry} material={materials.Plating_Mat} />
                            </group>
                          </group>
                          <group name="Flap_3_1" position={[337.164, 0, -695.955]}>
                            <group name="polySurface135_1" position={[4.697, 82.022, 300.755]} rotation={[0, -0.254, 0]}>
                              <mesh name="polySurface135_Light_Metal_Mat_0_1" geometry={nodes.polySurface135_Light_Metal_Mat_0_1.geometry} material={materials.Light_Metal_Mat} />
                              <mesh name="polySurface135_Dark_Metal_Mat_0_1" geometry={nodes.polySurface135_Dark_Metal_Mat_0_1.geometry} material={materials.Dark_Metal_Mat} />
                              <mesh name="polySurface135_Plating_Mat_0_1" geometry={nodes.polySurface135_Plating_Mat_0_1.geometry} material={materials.Plating_Mat} />
                            </group>
                          </group>
                          <group name="Flap_2_1" position={[-362.107, 0, -695.955]}>
                            <group name="polySurface137_1" position={[-4.697, 82.022, 300.755]} rotation={[0, 0.271, 0]}>
                              <mesh name="polySurface137_Light_Metal_Mat_0_1" geometry={nodes.polySurface137_Light_Metal_Mat_0_1.geometry} material={materials.Light_Metal_Mat} />
                              <mesh name="polySurface137_Dark_Metal_Mat_0_1" geometry={nodes.polySurface137_Dark_Metal_Mat_0_1.geometry} material={materials.Dark_Metal_Mat} />
                              <mesh name="polySurface137_Plating_Mat_0_1" geometry={nodes.polySurface137_Plating_Mat_0_1.geometry} material={materials.Plating_Mat} />
                            </group>
                          </group>
                          <group name="Flap_1_1" position={[-12.472, -349.635, -695.955]}>
                            <group name="polySurface136_1" position={[90.385, -4.697, 300.755]} rotation={[-0.254, 0.017, 0.004]}>
                              <mesh name="polySurface136_Light_Metal_Mat_0_1" geometry={nodes.polySurface136_Light_Metal_Mat_0_1.geometry} material={materials.Light_Metal_Mat} />
                              <mesh name="polySurface136_Dark_Metal_Mat_0_1" geometry={nodes.polySurface136_Dark_Metal_Mat_0_1.geometry} material={materials.Dark_Metal_Mat} />
                              <mesh name="polySurface136_Plating_Mat_0_1" geometry={nodes.polySurface136_Plating_Mat_0_1.geometry} material={materials.Plating_Mat} />
                            </group>
                          </group>
                          <group name="polySurface77_1" position={[-12.471, 460.733, 201.417]}>
                            <mesh name="polySurface77_Plating_Mat_0_1" geometry={nodes.polySurface77_Plating_Mat_0_1.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface77_Dark_Metal_Mat_0_1" geometry={nodes.polySurface77_Dark_Metal_Mat_0_1.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface80_1" position={[201.204, 383.495, 201.417]}>
                            <mesh name="polySurface80_Plating_Mat_0_1" geometry={nodes.polySurface80_Plating_Mat_0_1.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface80_Dark_Metal_Mat_0_1" geometry={nodes.polySurface80_Dark_Metal_Mat_0_1.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface81_1" position={[371.024, 213.675, 201.417]}>
                            <mesh name="polySurface81_Plating_Mat_0_1" geometry={nodes.polySurface81_Plating_Mat_0_1.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface81_Dark_Metal_Mat_0_1" geometry={nodes.polySurface81_Dark_Metal_Mat_0_1.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface82_1" position={[448.262, 0, 201.417]}>
                            <mesh name="polySurface82_Plating_Mat_0_1" geometry={nodes.polySurface82_Plating_Mat_0_1.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface82_Dark_Metal_Mat_0_1" geometry={nodes.polySurface82_Dark_Metal_Mat_0_1.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface83_1" position={[371.024, -213.675, 201.417]}>
                            <mesh name="polySurface83_Plating_Mat_0_1" geometry={nodes.polySurface83_Plating_Mat_0_1.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface83_Dark_Metal_Mat_0_1" geometry={nodes.polySurface83_Dark_Metal_Mat_0_1.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface84_1" position={[201.204, -383.495, 201.417]}>
                            <mesh name="polySurface84_Plating_Mat_0_1" geometry={nodes.polySurface84_Plating_Mat_0_1.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface84_Dark_Metal_Mat_0_1" geometry={nodes.polySurface84_Dark_Metal_Mat_0_1.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface85_1" position={[-12.471, -460.733, 201.417]}>
                            <mesh name="polySurface85_Plating_Mat_0_1" geometry={nodes.polySurface85_Plating_Mat_0_1.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface85_Dark_Metal_Mat_0_1" geometry={nodes.polySurface85_Dark_Metal_Mat_0_1.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface86_1" position={[-226.146, -383.495, 201.417]}>
                            <mesh name="polySurface86_Plating_Mat_0_1" geometry={nodes.polySurface86_Plating_Mat_0_1.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface86_Dark_Metal_Mat_0_1" geometry={nodes.polySurface86_Dark_Metal_Mat_0_1.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface87_1" position={[-395.966, -213.675, 201.417]}>
                            <mesh name="polySurface87_Plating_Mat_0_1" geometry={nodes.polySurface87_Plating_Mat_0_1.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface87_Dark_Metal_Mat_0_1" geometry={nodes.polySurface87_Dark_Metal_Mat_0_1.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface89_1" position={[-395.966, 213.675, 201.417]}>
                            <mesh name="polySurface89_Plating_Mat_0_1" geometry={nodes.polySurface89_Plating_Mat_0_1.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface89_Dark_Metal_Mat_0_1" geometry={nodes.polySurface89_Dark_Metal_Mat_0_1.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                          <group name="polySurface90_1" position={[-226.146, 383.495, 201.417]}>
                            <mesh name="polySurface90_Plating_Mat_0_1" geometry={nodes.polySurface90_Plating_Mat_0_1.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface90_Dark_Metal_Mat_0_1" geometry={nodes.polySurface90_Dark_Metal_Mat_0_1.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                        </group>
                        <group name="Engine_Body_1" position={[-49.914, 0, 0]}>
                          <mesh name="Engine_Body_Dark_Metal_Mat_0_1" geometry={nodes.Engine_Body_Dark_Metal_Mat_0_1.geometry} material={materials.Dark_Metal_Mat} />
                          <mesh name="Engine_Body_Plating_Mat_0_1" geometry={nodes.Engine_Body_Plating_Mat_0_1.geometry} material={materials.Plating_Mat} />
                          <mesh name="Engine_Body_Light_Metal_Mat_0_1" geometry={nodes.Engine_Body_Light_Metal_Mat_0_1.geometry} material={materials.Light_Metal_Mat} />
                          <mesh name="Engine_Body_Light_Mat_0_1" geometry={nodes.Engine_Body_Light_Mat_0_1.geometry} material={materials.Light_Mat} />
                        </group>
                      </group>
                      <group name="Body">
                        <group name="Clamps" position={[0, 21.73, -195.179]}>
                          <group name="pCylinder67" position={[-1144.769, 17.581, 153.581]}>
                            <mesh name="pCylinder67_Dark_Metal_Mat_0" geometry={nodes.pCylinder67_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                            <mesh name="pCylinder67_Plating_Mat_0" geometry={nodes.pCylinder67_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                          </group>
                          <group name="pCylinder66" position={[-1144.769, 17.581, -153.581]}>
                            <mesh name="pCylinder66_Dark_Metal_Mat_0" geometry={nodes.pCylinder66_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                            <mesh name="pCylinder66_Plating_Mat_0" geometry={nodes.pCylinder66_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                          </group>
                          <group name="pCylinder65" position={[-997.14, 0, -153.581]}>
                            <mesh name="pCylinder65_Plating_Mat_0" geometry={nodes.pCylinder65_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                          </group>
                          <group name="pCylinder64" position={[-997.14, 0, 153.581]}>
                            <mesh name="pCylinder64_Plating_Mat_0" geometry={nodes.pCylinder64_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                          </group>
                          <group name="pCylinder61" position={[1144.769, 17.581, -153.581]}>
                            <mesh name="pCylinder61_Dark_Metal_Mat_0" geometry={nodes.pCylinder61_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                            <mesh name="pCylinder61_Plating_Mat_0" geometry={nodes.pCylinder61_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                          </group>
                          <group name="pCylinder60" position={[997.14, 0, -153.581]}>
                            <mesh name="pCylinder60_Plating_Mat_0" geometry={nodes.pCylinder60_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                          </group>
                          <group name="pCylinder58" position={[997.14, 0, 153.581]}>
                            <mesh name="pCylinder58_Plating_Mat_0" geometry={nodes.pCylinder58_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                          </group>
                          <group name="pCylinder56" position={[1144.769, 17.581, 153.581]}>
                            <mesh name="pCylinder56_Dark_Metal_Mat_0" geometry={nodes.pCylinder56_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                            <mesh name="pCylinder56_Plating_Mat_0" geometry={nodes.pCylinder56_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                          </group>
                        </group>
                        <group name="Engine_Rot_01" position={[0, -114.195, -1533.069]}>
                          <group name="polySurface414" position={[0, 0, -62.488]}>
                            <mesh name="polySurface414_Light_Metal_Mat_0" geometry={nodes.polySurface414_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                          </group>
                        </group>
                        <group name="Engine_Rot_02" position={[0, -114.196, -3875.013]}>
                          <group name="polySurface491" position={[0, 0, -343.521]}>
                            <mesh name="polySurface491_Dark_Metal_Mat_0" geometry={nodes.polySurface491_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                        </group>
                        <group name="Engine_Rot_03" position={[-0.001, -114.196, -4029.924]}>
                          <group name="polySurface492" position={[0, 0, -362.111]}>
                            <mesh name="polySurface492_Dark_Metal_Mat_0" geometry={nodes.polySurface492_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          </group>
                        </group>
                        <group name="Door_Rot_1" position={[0.014, -1046.519, 207.011]}>
                          <group name="polySurface554">
                            <mesh name="polySurface554_Plating_Mat_0" geometry={nodes.polySurface554_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                          </group>
                        </group>
                        <group name="Door_Rot_2" position={[0, -998.976, 1040.498]}>
                          <group name="polySurface545" position={[0, 265.059, 74.423]}>
                            <group name="polySurface568">
                              <mesh name="polySurface568_Plating_Mat_0" geometry={nodes.polySurface568_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                            </group>
                          </group>
                          <group name="polySurface574" position={[-328.589, 111.585, 40.395]}>
                            <mesh name="polySurface574_Plating_Mat_0" geometry={nodes.polySurface574_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                          </group>
                        </group>
                        <group name="polySurface335" position={[0, 545.383, 2375.203]}>
                          <mesh name="polySurface335_Dark_Metal_Mat_0" geometry={nodes.polySurface335_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          <mesh name="polySurface335_Plating_Mat_0" geometry={nodes.polySurface335_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                          <mesh name="polySurface335_Solar_Panel_Mat_0" geometry={nodes.polySurface335_Solar_Panel_Mat_0.geometry} material={materials.Solar_Panel_Mat} />
                          <mesh name="polySurface335_Light_Metal_Mat_0" geometry={nodes.polySurface335_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                        </group>
                        <group name="pCube85" position={[0, 681.686, -2282.379]}>
                          <mesh name="pCube85_Plating_Mat_0" geometry={nodes.pCube85_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                        </group>
                        <group name="polySurface495" position={[0.009, -148.23, -2550.488]}>
                          <mesh name="polySurface495_Dark_Metal_Mat_0" geometry={nodes.polySurface495_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          <mesh name="polySurface495_Plating_Mat_0" geometry={nodes.polySurface495_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                          <mesh name="polySurface495_Light_Metal_Mat_0" geometry={nodes.polySurface495_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                        </group>
                        <group name="polySurface535" position={[0.009, -114.196, -3560.043]}>
                          <mesh name="polySurface535_Light_Metal_Mat_0" geometry={nodes.polySurface535_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                          <mesh name="polySurface535_Dark_Metal_Mat_0" geometry={nodes.polySurface535_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          <mesh name="polySurface535_Light_Mat_0" geometry={nodes.polySurface535_Light_Mat_0.geometry} material={materials.Light_Mat} />
                          <mesh name="polySurface535_Plating_Mat_0" geometry={nodes.polySurface535_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                        </group>
                        <group name="Cockpit_Glass" position={[0, 737.604, 3613.283]}>
                          <mesh name="Cockpit_Glass_Glass_Mat_0" geometry={nodes.Cockpit_Glass_Glass_Mat_0.geometry} material={materials.Glass_Mat} />
                          <mesh name="Cockpit_Glass_Dark_Metal_Mat_0" geometry={nodes.Cockpit_Glass_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          <mesh name="Cockpit_Glass_Plating_Mat_0" geometry={nodes.Cockpit_Glass_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                        </group>
                        <group name="polySurface562" position={[0, -714.1, 152.581]}>
                          <mesh name="polySurface562_Dark_Metal_Mat_0" geometry={nodes.polySurface562_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          <mesh name="polySurface562_Plating_Mat_0" geometry={nodes.polySurface562_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                          <mesh name="polySurface562_Light_Metal_Mat_0" geometry={nodes.polySurface562_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                          <mesh name="polySurface562_Light_Mat_0" geometry={nodes.polySurface562_Light_Mat_0.geometry} material={materials.Light_Mat} />
                        </group>
                        <group name="polySurface601" position={[0, 364.341, -100.398]}>
                          <group name="polySurface757">
                            <mesh name="polySurface757_Plating_Mat_0" geometry={nodes.polySurface757_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                            <mesh name="polySurface757_Dark_Metal_Mat_0" geometry={nodes.polySurface757_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                            <mesh name="polySurface757_Light_Metal_Mat_0" geometry={nodes.polySurface757_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                            <mesh name="polySurface757_Default_Material_0" geometry={nodes.polySurface757_Default_Material_0.geometry} material={materials.Default_Material} />
                            <mesh name="polySurface757_Glass_Mat_0" geometry={nodes.polySurface757_Glass_Mat_0.geometry} material={materials.Glass_Mat} />
                            <mesh name="polySurface757_Solar_Panel_Mat_0" geometry={nodes.polySurface757_Solar_Panel_Mat_0.geometry} material={materials.Solar_Panel_Mat} />
                          </group>
                        </group>
                        <group name="polySurface743" position={[773.11, -121.721, 1200.898]}>
                          <mesh name="polySurface743_Dark_Metal_Mat_0" geometry={nodes.polySurface743_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          <mesh name="polySurface743_Plating_Mat_0" geometry={nodes.polySurface743_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                        </group>
                        <group name="polySurface738" position={[-773.11, -121.721, 1200.898]}>
                          <mesh name="polySurface738_Plating_Mat_0" geometry={nodes.polySurface738_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                          <mesh name="polySurface738_Dark_Metal_Mat_0" geometry={nodes.polySurface738_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                        </group>
                        <group name="polySurface744" position={[0, -188.177, 1174.839]}>
                          <mesh name="polySurface744_Light_Metal_Mat_0" geometry={nodes.polySurface744_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                        </group>
                        <group name="polySurface758" position={[0, 180.671, -190.028]}>
                          <mesh name="polySurface758_Plating_Mat_0" geometry={nodes.polySurface758_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                        </group>
                        <group name="polySurface804" position={[0, -65.765, 1119.484]}>
                          <mesh name="polySurface804_Plating_Mat_0" geometry={nodes.polySurface804_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                          <mesh name="polySurface804_Dark_Metal_Mat_0" geometry={nodes.polySurface804_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          <mesh name="polySurface804_Light_Mat_0" geometry={nodes.polySurface804_Light_Mat_0.geometry} material={materials.Light_Mat} />
                          <mesh name="polySurface804_Light_Metal_Mat_0" geometry={nodes.polySurface804_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                        </group>
                      </group>
                      <group name="R_Wing" position={[-1305.992, -224.157, -8.417]}>
                        <group name="Engine_Rot" position={[-289.492, 64.569, 179.691]}>
                          <group name="polySurface162" position={[0, 0, 0.001]} rotation={[0.255, 0, 0]}>
                            <mesh name="polySurface162_Dark_Metal_Mat_0" geometry={nodes.polySurface162_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                            <mesh name="polySurface162_Plating_Mat_0" geometry={nodes.polySurface162_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                          </group>
                        </group>
                        <group name="Clamp_Trans" position={[-339.355, -91.445, 144.242]}>
                          <group name="polySurface181">
                            <mesh name="polySurface181_Light_Metal_Mat_0" geometry={nodes.polySurface181_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                          </group>
                        </group>
                        <group name="R_Wing_1" position={[-41.879, 0, 30.886]}>
                          <mesh name="R_Wing_Plating_Mat_0" geometry={nodes.R_Wing_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                          <mesh name="R_Wing_Dark_Metal_Mat_0" geometry={nodes.R_Wing_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          <mesh name="R_Wing_Light_Metal_Mat_0" geometry={nodes.R_Wing_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                        </group>
                      </group>
                      <group name="L_Wing" position={[1305.992, -224.157, -8.417]}>
                        <group name="Engine_Rot_1" position={[289.492, 64.569, 179.691]}>
                          <group name="polySurface162_1" rotation={[-0.236, 0, 0]}>
                            <mesh name="polySurface162_Dark_Metal_Mat_0_1" geometry={nodes.polySurface162_Dark_Metal_Mat_0_1.geometry} material={materials.Dark_Metal_Mat} />
                            <mesh name="polySurface162_Plating_Mat_0_1" geometry={nodes.polySurface162_Plating_Mat_0_1.geometry} material={materials.Plating_Mat} />
                          </group>
                        </group>
                        <group name="Clamp_Trans_1" position={[339.355, -91.445, 144.242]}>
                          <group name="polySurface181_1" position={[-299, 0, 0]}>
                            <mesh name="polySurface181_Light_Metal_Mat_0_1" geometry={nodes.polySurface181_Light_Metal_Mat_0_1.geometry} material={materials.Light_Metal_Mat} />
                          </group>
                        </group>
                        <group name="L_Wing_1" position={[41.879, 0, 30.886]}>
                          <mesh name="L_Wing_Plating_Mat_0" geometry={nodes.L_Wing_Plating_Mat_0.geometry} material={materials.Plating_Mat} />
                          <mesh name="L_Wing_Dark_Metal_Mat_0" geometry={nodes.L_Wing_Dark_Metal_Mat_0.geometry} material={materials.Dark_Metal_Mat} />
                          <mesh name="L_Wing_Light_Metal_Mat_0" geometry={nodes.L_Wing_Light_Metal_Mat_0.geometry} material={materials.Light_Metal_Mat} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/jet.gltf')
